### ISSUE TITLE
Project manager starts pyqt5 designer insteed of pyside6-designer

### ISSUE THREAD

**Issue by garawaa** [MadPonyInteractive/MadQt#11]
It should have executable choosing settings insteed of folder choosing for qt ui designer path settings.
For example I want to set it like D:\Python39\Scripts\pyside6-designer.exe

**Comment by MadPonyInteractive** [comment]
You are absolutely right.
At the moment I'm refactoring Project Manager, this fix will be in the next version.

Thank you

**Comment by garawaa** [comment]
Ok. thank you. By the way can I build qt designer plugin project to dll library?

**Comment by MadPonyInteractive** [comment]
Do you mean adding a QtDesigner plugin to the MadQt package?

**Comment by garawaa** [comment]
No. I want to build a dll file from python plugin project like standart cpp plugin. Then it will be easy to install the plugin.

**Comment by MadPonyInteractive** [comment]
I have no idea if you can or how would you have to do it.
